modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Dark-Utilities/issues"
license="Source: LGPL v2.1, Textures: ARR"

[[mods]]
modId="darkutils"
updateJSONURL="https://updates.blamejared.com/get?n=darkutils&gv=1.16.4"
version="${version}"
displayName="Dark Utilities"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.darkutils]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.darkutils]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.darkutils]]
    modId="bookshelf"
    mandatory=true
    versionRange="[9,)"
    ordering="AFTER"
    side="BOTH"